### ISSUE TITLE
UE 4.23.1 Inputs doesn't work when Packaged

### ISSUE THREAD

**Issue by gradgr** [ValveSoftware/steamvr_unreal_plugin#86] opened 2019-11-07 12:17 UTC
As title says Steam VR wont work while testing on Rift. I Can see the bindings for the app but nothing works... on editor everything is working as expected. Is there a fix or should we disable Valve's Input Plugin and go with legacy setup?

Using Binary versions of ue4+valve's plugin , from VR plugins only Steam VR is enabled.

Thank you!

[STEAM FORUM THREAD](https://steamcommunity.com/app/250820/discussions/7/1637549649098606356/)

**Comment by 1runeberg** [comment] 2019-11-07 18:44
Hi @gradgr - For 4.23 build issues, there's a workaround applied in the GitHub https://github.com/ValveSoftware/steamvr_unreal_plugin/tree/develop-4.23

It addresses an issue with Unreal Engine not properly reading custom input settings in builds.

We are looking at releasing this version to the Marketplace soon.

**Comment by gradgr** [comment] 2019-11-07 19:33
@1runeberg just thinking that when build on 4,23.1 for DX11, no input is taken into account, though motioncontroller play vibrations, just discovered that on ALT+TAB i get a DX11 error which seems to be an engine bug that introduced on 4.23.1 as on 4.23.0 never happend ( possible fix on .2 ) . Also with Steam VR on DX12 it seems that not inputs but HMD stucks after been worn and requires to kill the app. Apparently on Editor everything works fine :-) . When will 4.24 of plugin's version will be pushed at the marketplace?

**Comment by 1runeberg** [comment] 2019-11-07 20:51
hi @gradgr - not sure of DX issues with UE, but that likely needs to be raised with Epic Games directly to fix.

For 4.24, the latest stable version of our (Valve) plugin is already included in the engine.

**Comment by albatrossoftime** [comment] 2019-11-12 18:00
Afternoon all, just wanted to chip in - Index controller input also not working here in packaged builds for UE4 4.23.1, most recent version of marketplace SteamVRInput, SteamVR 1.8.20. Investigations continue.

Clarification:
- Orientation / Position : working fine
- Buttons/Triggers : no response

**Comment by 1runeberg** [comment] 2019-11-12 19:33
Hi @albatrossoftime - please see my first response on this thread. It applies to Index as well, the root cause is an issue with custom inputs with UE 4.23, this is unresolved from the Engine side but we've posted a work-around in our develop branches.

The code in the develop branches is a candidate release, so after final internal QA, we're hoping to release it in the Marketplace soon.

**Comment by albatrossoftime** [comment] 2019-11-15 18:45
@1runeberg Understood! I originally misunderstood your response, I thought you were talking about UE not recognizing the bindings within the Dashboard. Thanks for the continued support!

**Comment by 1runeberg** [comment] 2019-11-21 02:32
The latest update of the plugin is now already up in GitHub:
https://github.com/ValveSoftware/steamvr_unreal_plugin/releases

Marketplace version updates also sent to Epic, hopefully up within a few days :)

**Comment by albatrossoftime** [comment] 2019-11-22 20:01
Update: 
I've now tested the develop-4.23 branch, the 1.8.19 branch, and the current Marketplace version. At this time, none of them are recognizing input (other than device orientation) on packaged 64-bit builds. 
HOWEVER, they ARE recognizing input on 32-bit builds.
Attached is a raw System Report w/ the packaged build running.

Edit: Sorry for the awkward update right when you responded, just tried the 32-bit process and that is definitely getting the input.

[SteamVR-2019-11-22-AM_11_58_26.txt](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/3881200/SteamVR-2019-11-22-AM_11_58_26.txt)

**Comment by 1runeberg** [comment] 2019-11-22 20:10
Hi @albatrossoftime - 
from the logs, your project doesn't seem to be running the latest version of the plugin for UE4.23?

Can you also post a screenshot of the Bindings Dashboard please, in this area:
![image](https://user-images.githubusercontent.com/17371351/69457086-605fe280-0dc0-11ea-9513-373c34280c87.png)

**Comment by albatrossoftime** [comment] 2019-11-22 20:15
Sorry about that, I just noticed my VR monitor has been running for the past 3 hours and I've been switching configurations back and forth. I'll get you a clean report w/ the currently running version and that screen-cap momentarily. 
Also, just in case you missed my previous edit, I was able to get input on a 32-bit build, just not 64-bit builds yet.

64-bit raw report (not working):
[64bit_rawreport.txt](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/3881353/64bit_rawreport.txt)

32-bit raw report (working):
[32bit_rawreport.txt](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/3881354/32bit_rawreport.txt)


![vr_dashboard1](https://user-images.githubusercontent.com/15037184/69458703-d4e54380-0d24-11ea-813b-f5b35669382b.png)

![vr_dashboard2](https://user-images.githubusercontent.com/15037184/69458712-dca4e800-0d24-11ea-89df-9dcabc5bc099.png)

![plugin_version](https://user-images.githubusercontent.com/15037184/69458774-0231f180-0d25-11ea-9500-2df1c41417d0.png)

![plugin_version2](https://user-images.githubusercontent.com/15037184/69458872-39a09e00-0d25-11ea-8af2-114498c4f2da.png)

**Comment by 1runeberg** [comment] 2019-12-03 19:40
Closing for now, please reopen if you have any more questions on this. thanks.

**Comment by 1runeberg** [comment] 2019-12-03 19:46
Sorry, didnt realize you've made an edit on this -- I dont seem to get notifications for edits, so havent replied.

Anyways, we only support 64 bit actually, not 32 bit

For your Input, you need to revert to the Official Default Bindings --- Click on "View" for the Official Default Bindings in the Input Dashboard, then click on "Select This Binding"

Also, the dashboard screenshots you provided are for an Editor session not for a packaged one.

**Comment by 1runeberg** [comment] 2019-12-13 19:05
Closing for now, please feel free to reopen if you are still encountering issues.

If anyone else is seeing further problems, let us know and we can re-open this issue report :)

Cheers,
Rune

**Closed as completed by 1runeberg** 2019-12-13 19:05 UTC
Labels: help wanted
