### ISSUE TITLE
Motion controllers stop tracking on built project when plugin is enabled

### ISSUE THREAD

**Issue by dddubbb** [ValveSoftware/steamvr_unreal_plugin#50] opened 2019-06-26 05:42 UTC
Using 4.22.3 Everything works correctly in editor. 
In a packaged build the controllers still receive button input(teleport button still draws line, other buttons cycle movement as mapped) but are locked to the tracking origin. Making no other changes except disabling the SteamVR Input plugin fixes the issue.

Have mordentral's VR expansion plugin installed. Previously had his open vr input plugin installed but that has been removed. Chatted with mordentral on discord briefly trying to troubleshoot by removing his plugin and checking SteamVRbindings but couldn't find a fix.

**Comment by dddubbb** [comment] 2019-06-26 05:50
Downloaded and built the sample project, works perfectly.

**Comment by 1runeberg** [comment] 2019-06-26 05:53
Hi @dddubbb , can you send me the following info & files please:

1. Plugin version you are using (as quoted in the .uplugin file or Editor)
2. Whether you are using the Marketplace or GitHub version
3. Is your UE4.22.3 a binary version from the launcher or a custom Engine compile?
4. How are you packaging your project? Please provide me with any command line or if you are simply using the packaging from the Editor
5. Create a Development build, and provide me the binaries
6. Please provide me with your logs (project and shipping build)
7. All files under the YourProject\config directory (from your project source files)
8. All files under the YourGame\config directory (from the shipping build)
9. In SteamVR, open Developer > WebConsole
9.1 Click on VRServer category, click "Clear All"
9.2 Run your broken shipping build
9.3 Copy paste all entries in the WebConsole to a text file and send them off to me
9.4 A new category with your gamename should also appear in the WebConsole, select all entries here and paste to a text file and send them as well to me.

Thanks.

**Comment by 1runeberg** [comment] 2019-06-26 06:01
@dddubbb 

10. Your build logs for your broken shipping build.

**Comment by dddubbb** [comment] 2019-06-26 06:41
Sure thing!
1. Beta 1.0-sdk1.4.18
2. Marketplace (downloaded first day of release if that matters)
3. Binary version from launcher
4. File -> package project -> Windows -> 64 bit (Set to map only in project settings, including the one basic map with a mirror and the pawn)
5. Dev build: https://drive.google.com/open?id=16sR0Qtuu108so415xr59Xrgnksv3K-jM
6. Logs
[PIElog.log](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/3328611/PIElog.log)
[ShippingLog.txt](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/3328612/ShippingLog.txt)
7.project config
[ProjectConfig.zip](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/3328616/ProjectConfig.zip)
8. Game config
[GameConfig.zip](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/3328618/GameConfig.zip)
9. entries
[VRserverLog.txt](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/3328621/VRserverLog.txt)
[WebConsoleGameOutput.txt](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/3328623/WebConsoleGameOutput.txt)

10. Is this the same as 6?

Thanks for your help!

**Comment by 1runeberg** [comment] 2019-06-26 06:46
Hi... @dddubbb Thanks for the files!

I'm downloading them now and deleted your comment as it is public.

Sorry, I neglected to add where to send them : runeb@valvesoftware.com

For my reference, can you resend the links over to this email address please?

For 10, if the logs you have sent in 6 didnt include the earlier build process (for the broken shipping build), send me a copy of this as well.

Cheers,
Rune.

**Comment by dddubbb** [comment] 2019-06-26 07:12
You've probably already seen them but sent that through, thanks again for the help!

**Comment by 1runeberg** [comment] 2019-06-29 00:15
Working offline with @dddubbb . Appears to be an issue for builds with the OpenVRExpansion plugin (not the VRExpansion plugin)

**Comment by 1runeberg** [comment] 2019-07-02 00:23
Issue appears to be an unstable project due to a couple of engine & third-party plugin upgrades. 

Removing OpenVRExpansion in a simplified version of the project fixes the issue, although this cant be replicated in any other project. Motion sources in the simplified version are also missing.

Main project also exhibits an odd behavior of motion sources disappearing if the input plugin is removed. As motion sources aren't exposed by the input plugin, the only way this could potentially happen is if the SteamVR engine plugin is being disabled somehow in some other areas ofthe project.

Project was upgraded from lower engine versions, and can be causing instability issues, as the issues encountered is not replicable in any other project. 

Advised @dddubbb to look at the option of perhaps migrating current broken project assets to a stable project. 

Closing for now as this is very project specific rather than plugin specific, but please feel free to re-open if there's an issue that can be reproduced in a fresh project.

**Closed as completed by 1runeberg** 2019-07-02 00:23 UTC
Labels: good first issue, internal investigation

**Comment by uno1982** [comment] 2020-03-02 05:12
Was there ever a fix for this? I'm having the exact same issue on 4.22.3 with the latest steamvr input plugin

**Comment by uno1982** [comment] 2020-03-02 05:13
Also running VRExpansion and OpenVRExpansion Plugin's by MordenTral

**Comment by dddubbb** [comment] 2020-03-02 05:19
I ended up not using the SteamVR plugin. Looked into quite a bit with both Rune and MordenTral at the time and couldn't figure it out. You shouldn't need OpenVRExpansion with this, but if it's the same as mine enabling SteamVR with VRExpansion causes it. Might be worth checking in with Mordentral on Unreal Slackers discord. At the time it was just me but if more people have had this issue he might have a fix. I'd love to know here if there is one.

**Comment by uno1982** [comment] 2020-03-02 05:48
I have another project which uses both VRE and SteamVR input on 4.24.3 I'll be able to package shortly and update you on if its still an issue. Thanks for the update

**Comment by 1runeberg** [comment] 2020-03-02 23:54
This issue is related to the Marketplace version and the conflict between the two plugins at the time since part of  it was also doing input, I believe this has been corrected since.

However, there's a known issue with 4.24 that the Epic build team is still looking at.

Because the plugin is now one of the "select" plugins (along with other XR plugins)  that are on by default, it apparently goes through a different build proc, and there  runtime dependencies indicated in the build.cs files arent being honored. 

So you need to remember to manually copy the Config/SteamVRBindings folder for now in builds. This is discussed here:
https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/112

Please note that the engine will sometimes pick  bindings from the Engine\Config directory, so itll look like there are bindings there but in reality arent the correct project bindings.

as far as im aware it affects both source and launcher builds.

Ive been able to repro with C++ projects, the engine picking up the incorrect bindings.

For BP only projects, nothing gets packaged at all.

last update we have from Epic (last week) was it's not an easy fix. they might give us an alternative way of automating it, but for now it's open and their XR team is helping follow-up for us.

**Comment by uno1982** [comment] 2020-03-03 07:01
Thanks for the reply Rune. I've reviewed my plugin version which I did get from the marketplace but comparing the version number to the latest GitHub version i'm seeing that they are the same revision? I'm running a source build of 4.22.3 that I've cherry picked fixes for and outside of being able to get this plugin to work its the most stable and (bug free) version of the engine I've had since 4.19 hotfix. I copied this marketplace (4.22) plugin into my engine plugins/marketplace directory similar to what it would do for the binary engine instead of placing in my project (electric nodes is installed this way and I've never had issues before) but maybe I need to place it in my project folder as instructed on the GitHub docs? Another question is that when I package using dev I seem to have my bindings. The button mappings work and the files are present in windowsnoeditor/projectname/config/steamvrbindings and checking them does indeed show the correct json structure. I simply do not have tracking. I've updated the VRE and OpenVRExpansion plugin that Mordentral updated in Feb to remove the input refs from. It doesn't seem i'm having the same issues as described in #112. I also ran into the issues listed with having both the oculus and steamvr plugin active but found out that disabling the oculus plugin fixed the confusion the engine was having with sdk/steamvr inputs and binding corruption early on. VRE, OpenVRE, fingersolver, electricnodes, steamvr and steamvr input are my only plugins in the project. Any advice would be greatly appreciated.
![inputplugin](https://user-images.githubusercontent.com/45907836/75750223-5a479f00-5ce9-11ea-86ed-daf72efd0e5f.PNG)


I've been packaging without issue using legacy steamvr and oculus sdk inputs but due to knowing that 4.24 has this input binding method going forward and the only way to get true index support is using this plugin (due to missing keys from the legacy steamvr input) to explore all of the options I'd like to incorporate for input across all platforms I feel that this is the only path forward both from a project migration readiness standpoint and from a full index support standpoint.

**Comment by uno1982** [comment] 2020-03-10 01:05
Rune,

<details><summary>LogSteamVRInputDevice</summary><p>

```
LogSteamVRInputDevice: Display: SteamVR runtime 1.8.19 loaded.
[2020.03.10-00.46.02:177][  0]LogSteamVRInputDevice: Display: Action Manifest Path: ../../../DropIn/Config/SteamVRBindings/steamvr_manifest.json
[2020.03.10-00.46.02:177][  0]LogSteamVRInputDevice: Display: Controller Bindings Path: ../../../DropIn/Config/SteamVRBindings
[2020.03.10-00.46.02:180][  0]LogSteamVRInputDevice: Display: Temporary key [SteamVR_Input_Temporary_Action_1] for action [GripL] defined.
[2020.03.10-00.46.02:190][  0]LogSteamVRInputDevice: Display: Temporary key [SteamVR_Input_Temporary_Action_2] for action [GripR] defined.
[2020.03.10-00.46.02:198][  0]LogSteamVRInputDevice: Display: Temporary key [SteamVR_Input_Temporary_Action_3] for action [LaserBeamLeft] defined.
[2020.03.10-00.46.02:211][  0]LogSteamVRInputDevice: Display: Temporary key [SteamVR_Input_Temporary_Action_4] for action [LaserBeamRight] defined.
[2020.03.10-00.46.02:222][  0]LogSteamVRInputDevice: Display: Temporary key [SteamVR_Input_Temporary_Action_5] for action [TriggerL] defined.
[2020.03.10-00.46.02:231][  0]LogSteamVRInputDevice: Display: Temporary key [SteamVR_Input_Temporary_Action_6] for action [TriggerR] defined.
[2020.03.10-00.46.02:244][  0]LogSteamVRInputDevice: Display: Temporary key [SteamVR_Input_Temporary_Action_7] for action [ControllerMovementLeft,ControllerMovementLeft X Y_axis2d] defined.
[2020.03.10-00.46.02:244][  0]LogSteamVRInputDevice: Display: Temporary key [SteamVR_Input_Temporary_Action_8] for action [ControllerMovementLeft,ControllerMovementLeft X Y_axis2d] defined.
[2020.03.10-00.46.02:244][  0]LogSteamVRInputDevice: Display: Temporary key [SteamVR_Input_Temporary_Action_9] for action [ControllerMovementLeft axis] defined.
[2020.03.10-00.46.02:264][  0]LogSteamVRInputDevice: Display: Temporary key [SteamVR_Input_Temporary_Action_10] for action [ControllerMovementRight,ControllerMovementRight X Y_axis2d] defined.
[2020.03.10-00.46.02:264][  0]LogSteamVRInputDevice: Display: Temporary key [SteamVR_Input_Temporary_Action_11] for action [ControllerMovementRight,ControllerMovementRight X Y_axis2d] defined.
[2020.03.10-00.46.02:264][  0]LogSteamVRInputDevice: Display: Temporary key [SteamVR_Input_Temporary_Action_12] for action [ControllerMovementRight axis] defined.
[2020.03.10-00.46.02:272][  0]LogSteamVRInputDevice: Display: Temporary key [SteamVR_Input_Temporary_Action_13] for action [MotionControllerThumbLeft_X,MotionControllerThumbLeft_Y X Y_axis2d] defined.
[2020.03.10-00.46.02:273][  0]LogSteamVRInputDevice: Display: Temporary key [SteamVR_Input_Temporary_Action_14] for action [MotionControllerThumbLeft_X,MotionControllerThumbLeft_Y X Y_axis2d] defined.
[2020.03.10-00.46.02:297][  0]LogSteamVRInputDevice: Display: Temporary key [SteamVR_Input_Temporary_Action_15] for action [MotionControllerThumbRight_X,MotionControllerThumbRight_Y X Y_axis2d] defined.
[2020.03.10-00.46.02:297][  0]LogSteamVRInputDevice: Display: Temporary key [SteamVR_Input_Temporary_Action_16] for action [MotionControllerThumbRight_X,MotionControllerThumbRight_Y X Y_axis2d] defined.
[2020.03.10-00.46.02:329][  0]LogSteamVRInputDevice: Searching for Controller Bindings files at: ../../../DropIn/Config/SteamVRBindings
[2020.03.10-00.46.02:399][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Trying to load Action Manifest from: C:\Users\Jason\Downloads\Steamworks_sdk\tools\ContentBuilder\content\WindowsNoEditor\DropIn\Config\SteamVRBindings\steamvr_manifest.json
[2020.03.10-00.46.02:402][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Manifest Path Result: Success
[2020.03.10-00.46.02:402][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting main action set: Success
[2020.03.10-00.46.02:402][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/controllerleft
[2020.03.10-00.46.02:402][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:403][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/controllerright
[2020.03.10-00.46.02:403][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:403][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/special1
[2020.03.10-00.46.02:403][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:403][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/special2
[2020.03.10-00.46.02:403][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:403][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/special3
[2020.03.10-00.46.02:403][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:403][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/special4
[2020.03.10-00.46.02:403][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:404][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/special5
[2020.03.10-00.46.02:404][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:404][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/special6
[2020.03.10-00.46.02:404][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:404][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/special7
[2020.03.10-00.46.02:404][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:404][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/special8
[2020.03.10-00.46.02:404][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:404][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/skeletonleft
[2020.03.10-00.46.02:404][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:404][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/skeletonright
[2020.03.10-00.46.02:405][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:405][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/open_console
[2020.03.10-00.46.02:405][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:405][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/out/vibrateleft
[2020.03.10-00.46.02:405][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:405][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/out/vibrateright
[2020.03.10-00.46.02:405][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:405][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/GripL
[2020.03.10-00.46.02:405][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:405][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/GripL
[2020.03.10-00.46.02:405][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:405][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/GripL
[2020.03.10-00.46.02:405][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:405][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/GripL
[2020.03.10-00.46.02:405][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/GripR
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/GripR
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/GripR
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/GripR
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/LaserBeamLeft
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/LaserBeamLeft
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/LaserBeamLeft
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/LaserBeamRight
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/LaserBeamRight
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/LaserBeamRight
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/TriggerL
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/TriggerL
[2020.03.10-00.46.02:406][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:407][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/TriggerL
[2020.03.10-00.46.02:407][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:407][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/TriggerL
[2020.03.10-00.46.02:407][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:407][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/TriggerR
[2020.03.10-00.46.02:407][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:407][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/TriggerR
[2020.03.10-00.46.02:407][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:407][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/TriggerR
[2020.03.10-00.46.02:407][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:407][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/TriggerR
[2020.03.10-00.46.02:407][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:407][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/ControllerMovementLeft,ControllerMovementLeft X Y_axis2d
[2020.03.10-00.46.02:407][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:407][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/ControllerMovementLeft axis
[2020.03.10-00.46.02:407][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:407][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/ControllerMovementLeft,ControllerMovementLeft X Y_axis2d
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/ControllerMovementLeft axis
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/ControllerMovementRight,ControllerMovementRight X Y_axis2d
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/ControllerMovementRight axis
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/ControllerMovementRight axis
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/ControllerMovementRight axis
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/MotionControllerThumbLeft_X,MotionControllerThumbLeft_Y X Y_axis2d
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/MotionControllerThumbLeft_X,MotionControllerThumbLeft_Y X Y_axis2d
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/MotionControllerThumbLeft_X,MotionControllerThumbLeft_Y X Y_axis2d
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/MotionControllerThumbLeft_X,MotionControllerThumbLeft_Y X Y_axis2d
[2020.03.10-00.46.02:408][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:409][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/MotionControllerThumbRight_X,MotionControllerThumbRight_Y X Y_axis2d
[2020.03.10-00.46.02:409][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:409][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/MotionControllerThumbRight_X,MotionControllerThumbRight_Y X Y_axis2d
[2020.03.10-00.46.02:409][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:409][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/MotionControllerThumbRight_X,MotionControllerThumbRight_Y X Y_axis2d
[2020.03.10-00.46.02:409][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
[2020.03.10-00.46.02:409][  0]LogSteamVRInputDevice: Display: Retrieving Action Handle: /actions/main/in/MotionControllerThumbRight_X,MotionControllerThumbRight_Y X Y_axis2d
[2020.03.10-00.46.02:409][  0]LogSteamVRInputDevice: Display: [STEAMVR INPUT] Setting Action Handle Path Result: Success
```

</p></details>

My log is showing success both with the plugin in the engine and rebuilding and after moving the plugin into my projects directory and rebuilding. Both cases work in editor and result in no tracking after packaging but my bindings are working fine. The version matches the latest version on GitHub however I did grab it off marketplace and place into my projects folder. I'm unsure on how to troubleshoot this further. I can't move to 4.24 due to the network issues and 4.23 has its own horror stories. Outside of this plugin not working my 4.22.3 build is rock solid. Is there anyway to proceed?
