### ISSUE TITLE
Cosmos Bindings Missing? 4.24.3

### ISSUE THREAD

**Issue by uno1982** [ValveSoftware/steamvr_unreal_plugin#147] opened 2020-06-08 18:49 UTC
Is there any reason the Cosmos Bindings would be completely missing from UE4.24.3?

**Comment by uno1982** [comment] 2020-06-08 18:52
https://cdn.discordapp.com/attachments/322374743007297537/719615911660748890/unknown.png

**Comment by 1runeberg** [comment] 2020-06-08 21:04
Hi @uno1982 - From the screenshot, it looks like the SteamVR plugin isn't the active VR platform - can you check if the SteamVR plugin is enabled? 

If you are using an Oculus headset for your development, you can disable the Oculus SDK temporarily or place SteamVR in a higher priority in your DefaultEngine.ini like so:

[HMDPluginPriority]
OculusHMD=20
SteamVR=10

**Comment by uno1982** [comment] 2020-06-10 01:53
I don't have oculus sdk enabled at all I'm 100% steamvr I've also gotten others to test with a vanilla VR template and are facing the same issue. What I did was had someone send me a json export for the Cosmos so I could push it as the default bindings regardless of the engine input bindings. I've created a brand new project in both 4.24.3 and 4.25, disabled the oculus plugin restarted the editor and the results are the same in that the cosmos inputs simply do not list on the dropdown for input bindings.

**Comment by 1runeberg** [comment] 2020-06-10 02:32
Hi @uno1982 - can you send me your logs for the new vr project in either 4.24.3 or 4.25?

**Comment by uno1982** [comment] 2020-06-10 03:21
[Test_2.log](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/4756015/Test_2.log)
Here is the log from a fresh Vanilla VRTemplate.

**Comment by uno1982** [comment] 2020-06-10 03:22
![bindings](https://user-images.githubusercontent.com/45907836/84223517-b7e54780-aa9f-11ea-954f-1de006ccd9e2.PNG)

**Comment by uno1982** [comment] 2020-06-10 03:22
As you can see all steamvr inputs are available except cosmos

**Comment by 1runeberg** [comment] 2020-06-10 03:29
> [Test_2.log](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/4756015/Test_2.log)
> Here is the log from a fresh Vanilla VRTemplate.

Hi @uno1982 - it doesnt seem like you have a headset in your system? you need to have SteamVR running properly and with a headset in order to do any work with the plugin:

[2020.06.10-03.19.13:386][  0]LogHMD: Failed to initialize OpenVR with code 108

**Comment by uno1982** [comment] 2020-06-10 17:18
I have oculus rift s and index and have plugged them both in. My confusion comes from the fact I’ve never plugged in a wmr headset yet I still get the input bindings listed for actions in unreal editor. So why would cosmos need to be plugged in?

**Comment by uno1982** [comment] 2020-06-10 17:20
Plugging in either does load steamvr but does not create the cosmos keys

**Comment by uno1982** [comment] 2020-06-10 17:26
![](https://media.discordapp.net/attachments/416040783779463171/719627975594606622/unknown.png)
 
As you can see in 4.25 when loading from a 4.23 project the binding exist but the key is missing. It shows with the keyboard instead of a controller and looking for it results in no listing

**Comment by uno1982** [comment] 2020-06-10 17:30
So looking in source the keys are still there something in the module just isn’t loading them properly

**Comment by uno1982** [comment] 2020-06-10 17:44
[Test.log](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/4760275/Test.log)
Here is a copy of the log with steamvr loading properly and my vive pro plugged in
[2020.06.10-17.42.42:259][  0]LogHMD: SteamVR initialized.  Driver: lighthouse  Display: LHR-463FA5EB
Again this is a vanilla VR Template with no plugins installed. Also this is a binary launcher build of 4.24.3

**Comment by 1runeberg** [comment] 2020-06-10 18:32
The Cosmos keys doesn't have an OpenXR profile and Epic only adds XR keys native to the engine that are in the OpenXR standard (e.g. Index, WMR, Oculus, etc). 

That's why you see WMR keys as they aren't reliant on the activation of a XR plugin since WMR keys are engine native keys defined elsewhere in the engine.

The SteamVR plugin in Unreal augments the engine keys with the Cosmos keys (plus a couple of other keys not defined in the standard), so the plugin needs to be active and able to properly initialize SteamVR.

The Editor itself is a "game" and loads the plugins during startup, hence, the need for SteamVR to be active if the plugin is enabled (it should boot SteamVR up if it isnt).

Here's a quick test I just made with 4.24.3 from the Launcher version:

![image](https://user-images.githubusercontent.com/17371351/84304795-6969a300-ab9c-11ea-9acf-855687db0fab.png)


I've highlighted the areas that tell you if SteamVR is active. 

The keys get loaded early in the editor startup process so make sure there are no SteamVR errors when you are loading the editor, otherwise you may need to restart the Editor to see the keys.

**Comment by uno1982** [comment] 2020-06-10 21:53
I get everything except the cosmos you show there and I included the log earlier. I’ve also restarted the editor multiple times.

**Comment by 1runeberg** [comment] 2020-06-10 21:55
are you able to test on another PC? I just tried from another machine and I can't repro what you're seeing unfortunately.

**Comment by uno1982** [comment] 2020-06-10 21:56
I’ve had others try as well with the same results. I believe Mitch was having this issue as well

**Comment by 1runeberg** [comment] 2020-06-10 21:56
if you can provide a screenshot as well similar to mine along with steamvr in there as well so i can check if there's anything odd going on.

**Comment by 1runeberg** [comment] 2020-06-10 21:57
> I’ve had others try as well with the same results. I believe Mitch was having this issue as well

Im not sure who Mitch is?

**Comment by 1runeberg** [comment] 2020-06-10 21:58
is there a forum thread somewhere that I'm missing here?

**Comment by uno1982** [comment] 2020-06-10 22:02
So the first thing I guess I need to complain about is the complications of working with multiple projects and the constant need to strip my application from the steamvrsettings file every time I swap projects so the action manifest isn't "Mis matched"
   "application.generated.ue.virtual-reality-bp-game-template-11590370.ue4editor.exe" : {
      "knuckles_250820_AutosaveURL_steamvrinput" : "vr-input-workshop://2025770163",
      "knuckles_250820_NeedToUpdateAutosave_steamvrinput" : false,
      "knuckles_250820_PreviousURL_steamvrinput" : "vr-input-workshop://2025770163",
      "oculus_touch_250820_AutosaveURL_steamvrinput" : "vr-input-workshop://2026015391",
      "oculus_touch_250820_NeedToUpdateAutosave_steamvrinput" : false,
      "oculus_touch_250820_PreviousURL_steamvrinput" : "vr-input-workshop://2026015391",
      "vive_controller_250820_AutosaveURL_steamvrinput" : "vr-input-workshop://2025949219",
      "vive_controller_250820_NeedToUpdateAutosave_steamvrinput" : false,
      "vive_controller_250820_PreviousURL_steamvrinput" : "vr-input-workshop://2025949219"
   },
I constantly have to strip this out and add it back depending on the project I'm working on

**Comment by uno1982** [comment] 2020-06-10 22:03
That seems to be what the problem was with starting the new project. So this issue is resolved.

**Comment by 1runeberg** [comment] 2020-06-10 22:05
I mustve missed the mismatch error in the logs you provided, although that shouldnt really cause any missing keys from the UI itself.

**Comment by 1runeberg** [comment] 2020-06-10 22:06
at least from the last test.log you sent there isnt any mismatch error. but that really shouldnt matter for just seeing keys in the engine ui.

**Comment by uno1982** [comment] 2020-06-10 22:07
As soon as I removed those lines for the application from the steamvrsettings file under the steam config directory it corrected the issue.

**Comment by 1runeberg** [comment] 2020-06-10 22:14
must be something else going on as that's not related at all with custom engine keys. i normally work with multiple projects as well througout the day.

will be interesting to figure out the root cause. if you can send me your steamvr report and the project logs again with the mismatch error, as the one you posted here didnt seem to have them i can have a closer look.

so it seems you were experiencing the issue even before the mismatch error. and be interesting if you can repro the issue by bringing those entries back.

**Comment by uno1982** [comment] 2020-06-10 22:15
I think it has to do with those steamvr settings as they are directly related to the editor. By simply removing them it fixed the issue. But if I use the dev settings in steamvr to set defaults it will cause this issue again as it associates the editor as an app id and inserts those lines. I did open my other project without replacing those lines and my bindings are still working and the cosmos input did generate on load

**Comment by uno1982** [comment] 2020-06-10 22:19
![image](https://user-images.githubusercontent.com/45907836/84324576-83749880-ab3e-11ea-93d7-1b7f99c910b3.png)

**Comment by 1runeberg** [comment] 2020-06-10 22:37
The engine doesnt need the app registration for the keys, at least, the way I wrote it ;)

The engine will also crash if you attempt to run and the keys arent registered, as it has a valid keys check. So the state where the Editor is running in SteamVR mode but not showing the keys is a bit strange and I'd like to see what's causing it. esp the engine passing the keys check during startup but somehow not showing them in the UI.

we can do a live session on your machine so I can have a look and check for root cause?
runeb@valvesoftware.com

**Comment by uno1982** [comment] 2020-06-11 00:44
Testing between two vanilla VR templates caused a situation where modification to an action binding would have the cosmos missing but simply adding a new action binding would then cause the Cosmos to appear and then it would then be available within the engine until flipping between projects again. Repeating the "adding of a new action" would then refresh the list. For now this is a solid work around.

**Comment by 1runeberg** [comment] 2020-06-11 01:39
Thanks for your time doing a live session earlier @uno1982.

Just to clarify this a bit for others who might encounter this issue in the future and find themselves here:

The result from the investigation is the root cause appears to be in some setups, the Editor UI isn't properly refreshing the XR keys dropdown list in-between editor sessions for custom keys.

The custom keys are registered properly however, so simply adding a new key binding to an existing or new action will get the Editor UI to refresh the dropdown properly.

This behaviour doesnt seem to manifest in 4.25, but feel free to post here for anyone encountering issues on that version.

Cheers,
Rune

**Closed as completed by 1runeberg** 2020-06-11 01:39 UTC
Labels: good first issue
