### ISSUE TITLE
Crashes when SteamVR shuts down during editor use

### ISSUE THREAD

**Issue by muchcharles** [ValveSoftware/steamvr_unreal_plugin#1] opened 2019-04-12 18:10 UTC
This crash happened after closing SteamVR manually, and then reopening it, while the editor was running but not in VR Preview (didn't crash until reopened, but I'm not sure if reopening is what really triggered it):

![image](https://user-images.githubusercontent.com/7025369/56057044-ddf04a00-5d2b-11e9-8c3f-650ae9598d62.png)

It didn't crash until steamvr reopened, but this was the last thing in the log before visual studio got the crash:

    [2019.04.12-07.15.41:606][193]LogHMD: SteamVR Shutting down.

-----

And this second one crashed during a different run, when WMR timed out and closed SteamVR while the editor was open:

[steamvrinputcrash_04122019.txt](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/3074633/steamvrinputcrash_04122019.txt)

Seems all the VRInput null checks only work to protect against initial uninitialization, because VRInput never gets nulled out later on steamvr shutdown.  'SteamVR Shutting down' again immediately preceded the crash (seen in top of log, and the createproc error just below that can be ignored (it is noise about the crash reporter failing to start)).

**Comment by 1runeberg** [comment] 2019-04-17 05:54
Adding Discord thread on this so far for posterity...

**muchcharles | Into Arcade™Last Saturday at 4:12 AM**
@Rune Berg https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/1
GitHub
Crashes when SteamVR shuts down during editor use · Issue #1 · V...
This crash happened after closing SteamVR manually, and then reopening it, while the editor was running but not in VR Preview (didn't crash until reopened, but I'm not sure if reopening is ...

this was a couple lines before crash dump on pastebin (added it to what I put on github)
[2019.04.12-07.06.58:972][ 41]LogCore: Display: AppLifetime: Application will enter background
[2019.04.12-07.13.47:477][315]LogHMD: SteamVR Shutting down.


So HMD plugin had just finished handling a shutdown event

**Rune BergLast Saturday at 4:34 AM**
ah.. nice @muchcharles | Into Arcade™ , that helps. and explains the issue. just need to find an openvr way of a workaround - possibly use the same fix used in the oculus patch done by Keith.

**muchcharles | Into Arcade™Yesterday at 10:20 AM**
@Rune Berg awesome! just let me know
@Rune Berg one thing to watch out for in case your fix interacts, 4.22 changelog had this:

Bug Fix: SteamVR will now be restarted if it was shutdown while UE4 is running and a play-in-editor session is started.

**Rune BergToday at 7:17 AM**
@muchcharles | Into Arcade™  - ive published a develop-4.22 branch
VRSystem never gets nulled as expected as (at least the later versions of OpenVR) expects developers to use the function calls instead of caching.
theres a bit of a disconnect we had to juggle because (at least in older versions of the engine), the hmd module caches the VRSystem  - we are developing a PR for this to give back to Epic.
In the meantime, try out the code in develop-4.22, and let me know if it still crashes for you when you close SteamVR during an editor session.

**muchcharles | Into Arcade™Today at 1:28 PM**
@Rune Berg crash on restart of steamvr, probably VRSystem() begins  returning non-null again, but old VRInput pointer has been invalidated
Rune BergToday at 3:48 PM
thanks @muchcharles | Into Arcade™ !  Have just tried a couple of diff repro steps and deeper tracing.

seems like that Epic HMD SteamVR fix for 4.22, may actually allow us to go back to an earlier state of the plugin using pure function calls. 

Have done the codework but will have to do some internal regression testing before publishing. will ping ya either here or directly on the issue once its  published. most likely tomorrow.

**Comment by 1runeberg** [comment] 2019-04-18 04:40
**Update** 
Solution now ready for this with backwards compatibility up to UE4.15 
Cleaning up code in progress before publishing.

**Comment by 1runeberg** [comment] 2019-04-18 21:30
temp branch: develop-internal holds a fix for 4.15, doing internal investigation for Packaged builds failing at VRInput() calls

**Comment by 1runeberg** [comment] 2019-04-23 22:07
Fixed in internal branches. Will be in 0.6 release.

**Closed as completed by 1runeberg** 2019-04-23 22:07 UTC
Labels: bug
